"use client";

import { useState } from "react";
import Link from "next/link";
import {
  Eye,
  EyeOff,
  Sparkles,
  LineChart,
  ArrowRight,
  GraduationCap,
} from "lucide-react";

export default function SignUp() {
  const [showPassword, setShowPassword] = useState(false);

  return (
    <div className="min-h-screen flex flex-col font-sans text-slate-900 bg-white">
      {/* Main Split Content */}
      <div className="flex-1 flex flex-col lg:flex-row">
        {/* Left Panel - Branding & Features (Hidden on small screens) */}
        <div className="hidden lg:flex lg:w-1/2 bg-[#0a0f1c] bg-gradient-to-br from-[#16123f] to-[#0a0f1c] text-white p-12 xl:p-20 flex-col justify-between relative overflow-hidden">
          {/* Abstract background blur effect */}
          <div className="absolute top-0 left-0 w-full h-full overflow-hidden pointer-events-none">
            <div className="absolute top-[-10%] left-[-10%] w-2/3 h-2/3 rounded-full bg-indigo-600/10 blur-[120px]"></div>
            <div className="absolute bottom-[-10%] right-[-10%] w-2/3 h-2/3 rounded-full bg-purple-600/10 blur-[120px]"></div>
          </div>

          <div className="relative z-10 flex flex-col h-full">
            <div>
              <div className="flex items-center gap-3 mb-16">
                <div className="bg-indigo-600 p-2 rounded-lg">
                  <GraduationCap className="w-6 h-6 text-white" />
                </div>
                <span className="text-2xl font-bold tracking-tight">
                  CareerPath
                </span>
              </div>

              <div className="max-w-xl">
                <h1 className="text-5xl xl:text-6xl font-extrabold tracking-tight leading-tight mb-6">
                  The architect of your intellectual journey.
                </h1>
                <p className="text-lg text-slate-300 leading-relaxed max-w-md">
                  Join a community of scholars and professionals. Our
                  precision-engineered assessments map your potential to
                  real-world career trajectories.
                </p>
              </div>

              {/* Feature Cards */}
              <div className="grid grid-cols-2 gap-6 mt-12 max-w-xl">
                <div className="bg-white/5 border border-white/10 backdrop-blur-sm rounded-2xl p-6">
                  <LineChart className="w-6 h-6 text-indigo-400 mb-4" />
                  <h3 className="font-bold text-white mb-2 text-lg">
                    Deep Assessment
                  </h3>
                  <p className="text-slate-400 text-sm leading-relaxed">
                    Psychometric mapping tailored for modern roles.
                  </p>
                </div>
                <div className="bg-white/5 border border-white/10 backdrop-blur-sm rounded-2xl p-6">
                  <Sparkles className="w-6 h-6 text-purple-400 mb-4" />
                  <h3 className="font-bold text-white mb-2 text-lg">
                    AI Insights
                  </h3>
                  <p className="text-slate-400 text-sm leading-relaxed">
                    Precision career paths generated by expert data.
                  </p>
                </div>
              </div>
            </div>

            {/* Bottom Tagline */}
            <div className="mt-auto pt-12">
              <p className="text-xs font-bold text-slate-500 uppercase tracking-[0.2em]">
                Academic Rigor • Professional Clarity • Career Growth
              </p>
            </div>
          </div>
        </div>

        {/* Right Panel - Sign Up Form */}
        <div className="flex-1 flex flex-col justify-center px-8 sm:px-16 lg:px-24 py-12 lg:py-0 relative overflow-y-auto">
          {/* Mobile Header */}
          <div className="lg:hidden flex items-center gap-3 mb-10">
            <div className="bg-indigo-600 p-2 rounded-lg">
              <GraduationCap className="w-5 h-5 text-white" />
            </div>
            <span className="text-xl font-bold tracking-tight">CareerPath</span>
          </div>

          <div className="w-full max-w-lg mx-auto lg:mx-0 lg:max-w-md xl:max-w-lg">
            <div className="mb-10">
              <h2 className="text-3xl font-extrabold text-slate-900 mb-2">
                Create your account
              </h2>
              <p className="text-slate-500 text-lg">
                Begin your journey toward professional excellence.
              </p>
            </div>

            <form className="space-y-5" onSubmit={(e) => e.preventDefault()}>
              {/* Full Name */}
              <div className="space-y-2">
                <label className="text-[11px] font-bold text-slate-500 uppercase tracking-wider block">
                  Full Name
                </label>
                <input
                  type="text"
                  className="block w-full px-4 py-3.5 bg-slate-50/50 border border-slate-200 rounded-xl text-slate-900 placeholder-slate-400 focus:bg-white focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 transition-colors sm:text-sm"
                  placeholder="Alexander Sterling"
                  required
                />
              </div>

              {/* Username */}
              <div className="space-y-2">
                <label className="text-[11px] font-bold text-slate-500 uppercase tracking-wider block">
                  Username
                </label>
                <input
                  type="text"
                  className="block w-full px-4 py-3.5 bg-slate-50/50 border border-slate-200 rounded-xl text-slate-900 placeholder-slate-400 focus:bg-white focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 transition-colors sm:text-sm"
                  placeholder="scholarly_alex"
                  required
                />
              </div>

              {/* Email & Phone Row */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                <div className="space-y-2">
                  <label className="text-[11px] font-bold text-slate-500 uppercase tracking-wider block items-center gap-1">
                    Email{" "}
                    <span className="text-slate-400 font-medium normal-case">
                      (Optional)
                    </span>
                  </label>
                  <input
                    type="email"
                    className="block w-full px-4 py-3.5 bg-slate-50/50 border border-slate-200 rounded-xl text-slate-900 placeholder-slate-400 focus:bg-white focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 transition-colors sm:text-sm"
                    placeholder="alex@academy.edu"
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-[11px] font-bold text-slate-500 uppercase tracking-wider block items-center gap-1">
                    Phone{" "}
                    <span className="text-slate-400 font-medium normal-case">
                      (Optional)
                    </span>
                  </label>
                  <input
                    type="tel"
                    className="block w-full px-4 py-3.5 bg-slate-50/50 border border-slate-200 rounded-xl text-slate-900 placeholder-slate-400 focus:bg-white focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 transition-colors sm:text-sm"
                    placeholder="+1 (555) 000-0000"
                  />
                </div>
              </div>

              {/* Password */}
              <div className="space-y-2">
                <label className="text-[11px] font-bold text-slate-500 uppercase tracking-wider block">
                  Password
                </label>
                <div className="relative">
                  <input
                    type={showPassword ? "text" : "password"}
                    className="block w-full pl-4 pr-12 py-3.5 bg-slate-50/50 border border-slate-200 rounded-xl text-slate-900 placeholder-slate-400 focus:bg-white focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 transition-colors sm:text-sm"
                    placeholder="••••••••••••"
                    required
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                    className="absolute inset-y-0 right-0 pr-4 flex items-center"
                  >
                    {showPassword ? (
                      <EyeOff className="h-5 w-5 text-slate-400 hover:text-slate-600 transition-colors" />
                    ) : (
                      <Eye className="h-5 w-5 text-slate-400 hover:text-slate-600 transition-colors" />
                    )}
                  </button>
                </div>
              </div>

              {/* Checkbox */}
              <div className="flex items-start gap-3 pt-2">
                <div className="flex items-center h-5">
                  <input
                    id="terms"
                    type="checkbox"
                    className="w-4 h-4 text-indigo-600 border-slate-300 rounded focus:ring-indigo-500 cursor-pointer"
                    required
                  />
                </div>
                <label
                  htmlFor="terms"
                  className="text-sm text-slate-600 cursor-pointer"
                >
                  I agree to the{" "}
                  <Link
                    href="/terms"
                    className="text-indigo-600 hover:text-indigo-700 font-medium"
                  >
                    Terms of Service
                  </Link>{" "}
                  and{" "}
                  <Link
                    href="/privacy"
                    className="text-indigo-600 hover:text-indigo-700 font-medium"
                  >
                    Privacy Policy
                  </Link>
                  .
                </label>
              </div>

              {/* Submit Button */}
              <div className="pt-4">
                <button
                  type="submit"
                  className="w-full flex justify-center items-center gap-2 py-4 px-4 border border-transparent rounded-xl shadow-md shadow-indigo-600/10 text-sm font-bold text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-all"
                >
                  Create Account
                  <ArrowRight className="w-4 h-4" />
                </button>
              </div>
            </form>

            {/* Log in link */}
            <div className="mt-8 text-center">
              <p className="text-sm text-slate-600 font-medium">
                Already have an account?{" "}
                <Link
                  href="/auth/login"
                  className="text-indigo-600 font-bold hover:text-indigo-500"
                >
                  Log In
                </Link>
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Global Footer */}
      <footer className="border-t border-slate-100 bg-[#fafafa] py-6 px-8 flex flex-col sm:flex-row justify-between items-center gap-4 text-sm">
        <div className="font-bold text-slate-900">CareerPath</div>
        <div className="text-slate-500 text-xs">
          © {new Date().getFullYear()} CareerPath. Precision in Career Growth.
        </div>
        <div className="flex items-center gap-6">
          <Link
            href="/privacy"
            className="text-slate-500 hover:text-slate-800 text-xs font-medium transition-colors"
          >
            Privacy Policy
          </Link>
          <Link
            href="/terms"
            className="text-slate-500 hover:text-slate-800 text-xs font-medium transition-colors"
          >
            Terms of Service
          </Link>
          <Link
            href="/cookies"
            className="text-slate-500 hover:text-slate-800 text-xs font-medium transition-colors"
          >
            Cookie Policy
          </Link>
        </div>
      </footer>
    </div>
  );
}
